version: '3.8'
networks:
  default:
    external:
      name: kind
services:
  broker:
    image: cfplatformeng/csb
    ports:
      - "8080:8080"
    volumes:
      - .:/brokerpaks
    working_dir: /brokerpaks
    entrypoint: ["/bin/cloud-service-broker"]
    command: ["serve"]
    depends_on:
      - database
    restart: on-failure
    environment:
      DB_TLS: skip-verify
      DB_HOST: database
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_PORT: 3306
      SECURITY_USER_NAME: user
      SECURITY_USER_PASSWORD: pass
      GSB_API_HOSTNAME: broker
      PORT: 8080

  database:
    image: mysql:latest
    volumes:
      - database_data:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: servicebroker
    ports:
      - "3306:3306"
volumes:
  database_data:
