# On pull request events, this workflow will run `make build-and-test`. 
# On push events to the main branch, this workflow will upload a date-named release 

name: 'Test and (Maybe) Release'

on:
  push:
    branches:
    - 'main'
  pull_request:

jobs:
  make:
    name: 'Make'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Create KinD cluster
      uses: helm/kind-action@v1.0.0

    - name: Install the eden OSBAPI CLI tool
      run: |
        wget -q -O - https://raw.githubusercontent.com/starkandwayne/homebrew-cf/master/public.key | sudo apt-key add -
        echo "deb http://apt.starkandwayne.com stable main" | sudo tee /etc/apt/sources.list.d/starkandwayne.list
        sudo apt-get update
        sudo apt-get install eden

    - name: Check out repository
      uses: actions/checkout@v2
      with: 
        fetch-depth: '0'

    - name: Build the brokerpak and set up the test environment
      run: make build test-env-up 
    
    # - name: Stop for debugging
    #   uses: mxschmitt/action-tmate@v3
    #   with:
    #     limit-access-to-actor: true  
    
    - name: Start the broker and run the tests
      run: make up test

    - name: Bump version and push tag
      id: bump
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main
        INITIAL_VERSION: 0.0.0

    - name: Release pushes to main
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.brokerpak
        tag_name: ${{ steps.bump.outputs.new_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

