# On pull request events, this workflow will run `make build-and-test`. 
# On push events to the main branch, this workflow will upload a date-named release 

name: 'Test and (Maybe) Release'

on:
  push:
    branches:
    - '**'
  pull_request:

jobs:
  make:
    name: 'Make'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    # Checkout the repository to the GitHub Actions runner
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: '0'

        # TODO: 
        # 1. We need to figure out how to have a k8s available while the GitHub
        #    Action is running. 
        # 2. We need to figure out how to automate population of the
        #    examples.json file from the kubeconfig for that ephemeral k8s
    - name: Populate the examples.json file
      run: cp .env.secrets-template .env.secrets

    - name: Build and run examples (tests)
      run: make build up wait wait test

    - name: Bump version and push tag
      id: bump
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main
        INITIAL_VERSION: 0.0.0

    - name: Release pushes to main
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.brokerpak
        tag_name: ${{ steps.bump.outputs.new_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

