# On pull request events, this workflow will run `make build-and-test`. 
# On push events to the main branch, this workflow will upload a date-named release 

name: 'Test and (Maybe) Release'

on:
  push:
    branches:
    - '**'
  pull_request:

jobs:
  make:
    name: 'Make'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Create KinD cluster
      env: 
        INPUT_CLUSTER_NAME: kind
      uses: helm/kind-action@v1.0.0

    - name: Check out repository
      uses: actions/checkout@v2
      with: 
        fetch-depth: '0'

    - name: Build and run examples (tests)
      run: make build up wait wait test

    - name: Bump version and push tag
      id: bump
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main
        INITIAL_VERSION: 0.0.0

    - name: Release pushes to main
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.brokerpak
        tag_name: ${{ steps.bump.outputs.new_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

