# On pull request events, this workflow will run `make build-and-test`. 

name: 'test'
on:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Debug (primarily for brokerpak provisioning constraints)'
        required: false
        default: false

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Create KinD cluster
      uses: helm/kind-action@v1.2.0

    - name: Install the eden OSBAPI CLI tool
      run: |
        wget -q -O - https://raw.githubusercontent.com/starkandwayne/homebrew-cf/master/public.key | sudo apt-key add -
        echo "deb http://apt.starkandwayne.com stable main" | sudo tee /etc/apt/sources.list.d/starkandwayne.list
        sudo apt-get update
        sudo apt-get install eden
        sudo apt-get install bats

    - name: Check out repository
      uses: actions/checkout@v2
      with: 
        fetch-depth: '0'

    - name: Build the brokerpak and set up the test environment
      run: make build test-env-up 
    
    - name: Stop for debugging
			if: github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true  
    
    - name: Start the broker and run the tests
      run: make up test

    - name: Clean up if there was a failure
      if: ${{ failure() }}
      run: make down
